### ISSUE TITLE
P39「λ」記号が使えない

### ISSUE THREAD

**Issue by shinriyo** [jinjor/elm-book#5]
P39に「ラムダ記号(`λ`、`\`)を使って記述します。」とあるが、
`\`の代わりに`λ`を使用するとエラーになります。

```
> \n -> n < 0
<function> : number -> Bool
```
本文にある上のは実行可能。

同様に以下のように記載すると実行不可能。
```
> λn -> n < 0
-- PARSE ERROR ------------------------------------------------------------- elm

I was not expecting this arrow while parsing repl_value_1's definition.

3| repl_value_1 =
4|   λn -> n < 0
        ^
An arrow should only appear in cases expressions and anonymous functions. Maybe
you want > or >= instead?
```

P15の記載通り、`0.19`を使用しています。

```
> elm --version
0.19.0
```

**Comment by NaokiM03** [comment]
0.18 までしか使えないみたいです。
[The \`symbol\` operator cannot handle non-ASCII stuff](https://github.com/elm/compiler/commit/891af27f5f6b5828ffca6a640b487f3aa45d4405)

**Comment by shinriyo** [comment]
@NaokiM03 ありがとうございます。
本書の前提条件のバージョンを下げるか、0.18 までは使えてたかの注釈が必要ですね。

**Comment by jinjor** [comment]
いつの間にか使えなくなっていたのですね。
報告ありがとうございます。

**Comment by jinjor** [comment]
readme に追記しました
